### PR TITLE
Changes to the breadcrumb and display of French menu blocks

### PR DESCRIPTION
**Pull request by jeffdavidgordon**

### CODE REVIEW

**Comment by sylus** [comment]
You need to run phpcs against your code as is failing. All of our files adhere to phpcs spec.

https://travis-ci.org/open-data/od/builds/324598786#L2508

**Comment by sylus** [comment]
Woot woot all good!

Just make sure you squash and merge now :)

**Comment by sylus** [comment]
Oh wait I still see commented out code that shouldnt be there

// $variables['content']['top_left'][$value]['#access'] = FALSE;

**Comment by sylus** [comment]
Without those menu block visibility rules you will have both en + fr menu blocks showing in top_left region as you sure u wanted logic removed? (edited)

**Comment by jeffdavidgordon** [comment]
Yes I do, I've changed a bit how the menus work so this logic needed to be removed.

**Comment by sylus** [comment]
Ah k just wanted to make sure :) should be all good to merge after this, and process is pretty much the same for all future P.R.s. :)

You should have full administrative privileges on the repo, so can just squash and merge when is green. :)

Thanks a bunch!

**Comment by jeffdavidgordon** [comment]
Thanks!

**Pull request merged**
